#!/bin/bash

set -e

# Send the log output from this script to custom-data.log
exec >>tee /var/log/custom-data.log 2>&1

sudo echo '${consul_config}' > /etc/consul.d/config/config.json

sudo chown consul:consul /etc/consul.d/config/config.json

systemctl daemon-reload
systemctl start consul.service
systemctl enable consul.service
