#!/bin/bash -eux

# Send the log output from this script to custom-data.log
exec 2> >(sudo tee -a /var/log/custom-data.log)

sudo echo '${consul_config}' > /etc/consul.d/config/config.json

sudo chown consul:consul /etc/consul.d/config/config.json

sudo systemctl daemon-reload
sudo systemctl start consul.service
sudo systemctl enable consul.service
